# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    # machine: true
    # environment:
    #   - DOCKER_IMAGE_REPO: meganii/dockerfile-mecab-python3
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: meganii/docker-mecab-hugo

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Setup git user
          command: |
            git config --global user.email "yuhei24@gmail.com"
            git config --global user.name "megnaii"

      # run tests!
      - run:
          name: run tests
          command: |
            python script/vectorize_text.py
            hugo version
            ruby -v
            cat data/relatedposts.yml

      - deploy:
          name: Git push
          command: |
            git add data/* tmp/* && git commit -m "[ci skip] publish"; if [ $? -eq 0 ]; then git push origin master; else :; fi

      - store_artifacts:
          path: test-reports
          destination: test-reports
