# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    # machine: true
    # environment:
    #   - DOCKER_IMAGE_REPO: meganii/dockerfile-mecab-python3
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: frolvlad/alpine-python3:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      # - run: docker pull $DOCKER_IMAGE_REPO:latest
      # - run: docker build -t circleci --cache-from $DOCKER_IMAGE_REPO:latest .
      # - run: docker tag circleci $DOCKER_IMAGE_REPO:latest
      # - run: docker push $DOCKER_IMAGE_REPO:latest

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pip install numpy scipy scikit-learn

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python --version

      - store_artifacts:
          path: test-reports
          destination: test-reports
